### ISSUE TITLE
Redmine 3.2.1 rake db error

### ISSUE THREAD

**Issue by archonwang** [brunofonseca/redmine_issue_templates_notes#3]
Thanks.
error logs as follows: 

> An error occurred while loading the routes definition of redmine_issue_templates_notes plugin (/opt/redmine/plugins/redmine_issue_templates_notes/config/routes.rb): You should not use the `match` method in your router without specifying an HTTP method.
> If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
> If you want to expose your action to GET, use `get` in the router:
>   Instead of: match "controller#action"
>   Do: get "controller#action".

**Comment by brunofonseca** [comment]
Hi @archonwang !

Thank you for using the Issue Template Notes plugin for Redmine,

I did not quite understand your notification. Was it a change request or a warning in the use of routes without specifying the verb?

I used it this way, because I need to use non-REST, updates and other actions inside the plugin, which had a lot of difficulty when I was creating it in 2014.

I apologize for the long delay. I have some other comments on the plugin, and I'll create a checklist of considerations, more sure your will join this checklist.

Thanks in advance for the alert!

**Comment by archonwang** [comment]
@brunofonseca , Thanks for your reply.

I think I used redmine 3.3 and it occured for the rails method has been changed. please check it. Thanks

my environment is

```
Environment:
  Redmine version                3.3.1.stable.16076
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```
